// Mar_Lectures/19_03_2025/ourbank/src/pages/NetBanking.jsx
import React, { useState } from "react";
import Navigation from "../components/Navigation";
import { Link } from "react-router-dom";
import axios from "axios";
import { useNavigate } from "react-router-dom";
import { useDispatch, useSelector } from "react-redux";
import { login_User } from "../reduxContainer/AuthAction";


function NetBanking() {
    const navigate = useNavigate();
    const dispatch = useDispatch();
    const [msg, setMsg] = useState('');
    const [user, setUser] = useState({
        username: '',
        password: ''
    })

    const assignData = (e) => {
        setUser({ ...user, [e.target.name]: e.target.value});
    }

    const loginUser = (e) => {
        e.preventDefault();
        axios.post('http://localhost:8080/login', user)
            .then((res) => {
                console.log(res.data);
                if (res.data.success === false || !res.data.email) {
                    setMsg('Incorrect Username Or Password');
                } else {
                    dispatch(login_User(res.data));
                    navigate('/user');
                }
            })
            .catch((err) => {
                console.error(err);
                setMsg('Server Error');
            });
    }

  return (
    <div class="container">
      <Navigation />
      <section class="main">
        <h2>Net Banking</h2>
        <div class="contact-form">
          <form action="">
            <h3>Login to Your Account</h3>
            <div class="form-group">
              <label for="name">Username</label>
              <input
                type="text"
                id="username"
                name="username"
                value={user.username}
                onChange={assignData}
                placeholder="Enter your full name"
                required
              />
            </div>
            <div class="form-group">
              <label for="name">Password</label>
              <input
                type="text"
                id="password"
                name="password"
                value={user.password}
                onChange={assignData}
                placeholder="Enter your password"
                required
              />
            </div>
            <button type="submit" class="submit-btn" onClick={loginUser}>
              Login
            </button>
            <br />
            <br />
            <p>
              Don't have an account? <Link to="/register">Register</Link>
            </p>
            <h1 className='error'>{msg}</h1>
          </form>
        </div>
      </section>
    </div>
  );
}

export default NetBanking;

// Mar_Lectures/19_03_2025/our-bank/src/app/component/netbanking/netbanking.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, FormsModule, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { HttpClient} from '@angular/common/http';
import { NavigationComponent } from '../navigation/navigation.component';
import { CommonModule } from '@angular/common';
// Removed unused imports

@Component({
  selector: 'app-netbanking',
  imports: [NavigationComponent, FormsModule, ReactiveFormsModule, CommonModule],
  templateUrl: './netbanking.component.html',
  styleUrls: ['./netbanking.component.css']
})
export class NetbankingComponent {
  msg: string = '';
  loginForm: FormGroup;

  constructor(private fb: FormBuilder, private router: Router, private http: HttpClient) {
    this.loginForm = this.fb.group({
      username: ['', Validators.required],
      password: ['', Validators.required]
    });
  }

  loginUser(): void {
    if (this.loginForm.invalid) {
      this.msg = 'Please fill in all required fields.';
      return;
    }

    const user = this.loginForm.value;

    this.http.post('http://localhost:8080/login', user).subscribe({
      next: (res: any) => {
        if (!res.email) {
          console.log(res);
          this.msg = 'Incorrect Username Or Password';
        } else {
          console.log(res);
          this.router.navigate(['/user/balance-enquiry']);
        }
      },
      error: (err) => {
        console.error(err);
        this.msg = 'Server Error';
      }
    });
  }
}

<div class="container">
    <app-navigation></app-navigation>
    <section class="main">
        <h2>Net Banking</h2>
        <div class="contact-form">
            <form [formGroup]="loginForm" (ngSubmit)="loginUser()">
                <h3>Login to Your Account</h3>
                <div class="form-group">
                    <label for="username">Username</label>
                    <input 
                        type="text" 
                        id="username" 
                        formControlName="username" 
                        placeholder="Enter your full name" 
                        required>
                    <div *ngIf="loginForm.get('username')?.invalid && loginForm.get('username')?.touched" class="error-msg">
                        Username is required.
                    </div>
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input 
                        type="password" 
                        id="password" 
                        formControlName="password" 
                        placeholder="Enter your password" 
                        required>
                    <div *ngIf="loginForm.get('password')?.invalid && loginForm.get('password')?.touched" class="error-msg">
                        Password is required.
                    </div>
                </div>                  
                <button type="submit" class="submit-btn" [disabled]="loginForm.invalid">Login</button>
                <br>
                <br>
                <p>Don't have an account? <a routerLink="/register">Register</a></p>
                <p *ngIf="msg" class="error-msg">{{ msg }}</p>
            </form>
        </div>
    </section>
</div>
