// Mar_Lectures/06_03_2025/assignment/src/app/calculator/deposit-calculator/deposit-calculator.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-deposit-calculator',
  imports: [FormsModule, CommonModule],
  templateUrl: './deposit-calculator.component.html',
  styleUrl: './deposit-calculator.component.css'
})
export class DepositCalculatorComponent {
  return: number = 0;
  error: string = ""
  calculate(amount: string, tenure: string, interest: string): void {
    const tenureValue = parseFloat(tenure);
    if (tenureValue <= 0 || tenureValue >= 10) {
      this.error = "Tenure must be less than 10 years";
      this.return = 0;
      return;
    } else {
      this.error = "";
    }
   this.return = parseFloat(amount) * Math.pow(1 + parseFloat(interest) / 100, parseFloat(tenure));
}
}


    <section class="main" id="deposit_calculator">
        <h2>Deposit Calculator</h2>
        <br>
        <br>
        <div class="contact-form">
        <h3>Enter the below details</h3>
            <div class="form-group">
                <label for="amount">Principal Amount</label>
                <input type="number" placeholder="Enter Principal Amount" required #amount>
            </div>
            <div class="form-group">
                <label for="tenure">Tenure</label>
                <input type="number" placeholder="Enter Tenure" required #tenure>
            </div>
            <div class="form-group">
                <label for="interest">Interest</label>
                <input type="number" placeholder="Enter Interest" value=7 readonly #interest>
            </div>
            <button class="submit-btn" (click)="calculate(amount.value, tenure.value, interest.value)">Calculate Maturity</button>
            <br>
            <br>
            <h1 class="maturity" *ngIf="return > 0">{{return}}</h1>
            <a>{{error}}</a>
            <br>
        </div>
    </section>

// Mar_Lectures/12_03_2025_ReactJs/myapp/src/DepositCalculator.js
import React, { useState } from 'react'

function DepositCalculator() {
    const [amount, setAmount] = useState(0);
    const [tenure, setTenure] = useState(0);
    const [error, setError] = useState("");
    const [maturity, setMaturity] = useState(0);

    function calculateMaturity() {
        if (tenure > 7) {
            setError("Tenure for deposit should be less than or equal to 7 years.");
            return;
        }
        setMaturity(amount * Math.pow(1 + 7 / 100, tenure));
        setError("");
    }


  return (
    <section class="main" id="deposit_calculator">
            <h2>Deposit Calculator</h2>
            <div class="contact-form">
            <h3>Enter the below details</h3>
                    <div class="form-group">
                        <label for="amount">Principal Amount</label>
                        <input type="number" id="amount" name="amount" placeholder="Enter Principal Amount" required onChange={(e) => setAmount(e.target.value)}/>
                    </div>
                    <div class="form-group">
                        <label for="tenure">Tenure</label>
                        <input type="number" id="tenure" name="tenure" placeholder="Enter Tenure" required onChange={(e) => setTenure(e.target.value)}/>
                    </div>
                    <div class="form-group">
                        <label for="interest">Interest</label>
                        <input type="number" id="interest" name="interest" placeholder="Enter Interest" disabled value="7.0"/>
                    </div>
                    <button type="submit" class="submit-btn" onClick={calculateMaturity}>Calculate Maturity</button>
                    <br/>
                    <br/>
                    <h1 class="maturity">{maturity==0?"":maturity}  </h1>
                    <p>{error}</p>
                    <br/>
                </div>
        </section>
  )
}

export default DepositCalculator
