// Mar_Lectures/19_03_2025/ourbank/src/pages/Register.jsx
import React, { useState } from 'react'
import Navigation from '../components/Navigation'
import { Link } from 'react-router-dom'
import axios from 'axios';
import { useNavigate } from 'react-router-dom';


function Register() {

  const navigate = useNavigate();
  const [msg, setMsg] = useState('');
  const [user, setUser] = useState({
    fname: '',
    username: '',
    email: '',
    password: '',
    amount: 0
  })
  const assignData = (e) => {
    setUser({ ...user, [e.target.name]: e.target.value});
  }

  const registerUser = (e) => {
    e.preventDefault();
    console.log(user);
    axios.post('http://localhost:8080/register', user)
            .then((res) => {
                console.log('User Register Successfully', res.data);
                setMsg('User Register Successfully');
                navigate('/net-banking');
            })
            .catch((err) => {
                console.log(err);
                setMsg('Failed to Register User');
            });
  }

  return (
    <div className="container">
    <Navigation />
    <section className="main">
        <h2>Net Banking</h2>
        <div className="form-container">
        </div>
        <div className="contact-form">
            <form action="">
                <h3>Register for Net Banking</h3>
                <div className="form-group">
                    <label for="fname">Full Name</label>
                    <input type="text" id="fname" value={user.fname} onChange={assignData} name="fname" placeholder="Enter your full name" required />
                </div>
                <div className="form-group">
                    <label for="username">Username</label>
                    <input type="text" id="username" value={user.username} onChange={assignData} name="username" placeholder="Enter Username" required />
                </div>
                <div className="form-group">
                    <label for="email">Email Address</label>
                    <input type="email" id="email" value={user.email} onChange={assignData} name="email" placeholder="Enter your email address" required />
                </div>
                <div className="form-group">
                    <label for="password">Password</label>
                    <input type="password" id="password"value={user.password} onChange={assignData} name="password" placeholder="Enter your password" required />
                </div>
                <button type="submit" className="submit-btn" onClick={registerUser}>Register</button>
                <br />
                <br />
                <p>Already have an account? <Link to="/net-banking">Login</Link></p>
                <h1 className='error'>{msg}</h1>
            </form>
        </div>
    </section>
</div>
  )
}

export default Register

// Mar_Lectures/19_03_2025/our-bank/src/app/component/register/register.component.ts
import { Component } from '@angular/core';
import { NavigationComponent } from "../navigation/navigation.component";
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-register',
  imports: [NavigationComponent, RouterLink],
  templateUrl: './register.component.html',
  styleUrl: './register.component.css'
})
export class RegisterComponent {

}

<div class="container">
    <app-navigation></app-navigation>
    <section class="main">
        <h2>Net Banking</h2>
        <div class="form-container">
        </div>
        <div class="contact-form">
            <form action="">
                <h3>Register for Net Banking</h3>
                <div class="form-group">
                    <label for="name">Full Name</label>
                    <input type="text" id="fullname" name="fullname" placeholder="Enter your full name" required>
                </div>
                <div class="form-group">
                    <label for="name">Username</label>
                    <input type="text" id="username" name="username" placeholder="Enter Username" required>
                </div>
                <div class="form-group">
                    <label for="email">Email Address</label>
                    <input type="email" id="email" name="email" placeholder="Enter your email address" required>
                </div>
                <div class="form-group">
                    <label for="name">Password</label>
                    <input type="text" id="password" name="password" placeholder="Enter your password" required>
                </div>
                <button type="submit" class="submit-btn">Submit Message</button>
                <br>
                <br>
                <p>Already have an account? <a routerLink="/net-banking">Login</a></p>

            </form>
        </div>
    </section>
</div>
