// Mar_Lectures/19_03_2025/our-bank/src/app/component/balance-enquiry/balance-enquiry.component.ts
import { Component } from '@angular/core';
import { NavigationComponent } from "../navigation/navigation.component";
import { HttpClient } from '@angular/common/http';
import { BrowserModule } from '@angular/platform-browser';
import { HttpClientModule } from '@angular/common/http';
@Component({
  selector: 'app-balance-enquiry',
  imports: [NavigationComponent, HttpClientModule],
  templateUrl: './balance-enquiry.component.html',
  styleUrl: './balance-enquiry.component.css'
})
export class BalanceEnquiryComponent {
  user: any = null;
  balance: number = 0;

  constructor(private http: HttpClient) {}

  ngOnInit(): void {
    // Simulate fetching user data (replace with actual service call if needed)
    this.user = { id: 1 }; // Example user object

    if (this.user) {
      this.http.get<number>(`http://localhost:8080/checkBalance/${this.user.id}`)
        .subscribe({
          next: (data: number) => {
            this.balance = data;
            console.log(data);
          },
          error: (err: any) => {
          }
        });
    }
  }
}

<div class="container">
    <app-navigation></app-navigation>
    <main class="main">
        <h2>Bank Balance</h2>

        <div class="contact-container">
            <div class="contact-card">
                <h3>Welcome</h3>
                <div class="contact-info">
                    <p>Your current balance is:</p>
                    <h4>₹ {{ balance }}</h4>
                </div>
            </div>
        </div>
        
    </main>
</div>

// Mar_Lectures/19_03_2025/ourbank/src/pages/UserPages/BalanceEnquiry.jsx
import React, { useState } from "react";
import { Link } from "react-router-dom";
import CustomerNavigation from "../../components/CustomerNavigation";
import { useSelector } from "react-redux";
import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";

function BalanceEnquiry() {
    const User = useSelector((state) => state.user);
    const [balance, setBalance] = useState(0);

    useEffect(() => {
        if (User && User.length > 0) {
            axios
                .get("http://localhost:8080/checkBalance/" + User[0].id)
                .then((res) => {
                    setBalance(res.data);
                    console.log(res.data);
                })
                .catch((err) => {
                    console.log(err);
                });
        }
    }, [User]);

    return (
        <div className="container">
            <CustomerNavigation />
            <main className="main">
                <h2>Bank Balance</h2>

                <div className="contact-container">
                    <div className="contact-card">
                        <h3>Welcome, {User && User.length > 0 ? User[0].fname : "User"}</h3>
                        <div className="contact-info">
                            <p>Your current balance is:</p>
                            <h4>₹ {balance}</h4>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    );
}

export default BalanceEnquiry;
