// Mar_Lectures/19_03_2025/ourbank/src/components/Navigation.jsx
import React from 'react'
import './components.css'
import { Link } from 'react-router-dom'


function Navigation() {
  return (
    <aside class="aside">   
    <h3>Navigation</h3>
    <ul>
        <li><Link to="/">Home</Link></li>
        <li><Link to="/about-us">About Us</Link></li>
        <li><Link to="/services">Services</Link></li>
        <li><Link to="/net-banking">Net Banking</Link></li>
        <li><Link to="/contact-us">Contact Us</Link></li>
    </ul>
</aside>
  )
}

export default Navigation

// Mar_Lectures/05_03_2025_Angular/our-bank/src/app/component/navigation/navigation.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-navigation',
  imports: [RouterLink],
  templateUrl: './navigation.component.html',
  styleUrl: './navigation.component.css'
})
export class NavigationComponent {

}


<aside class="aside">   
    <h3>Navigation</h3>
    <ul>
        <li><a routerLink="/home">Home</a></li>
        <li><a routerLink="/about-us">About Us</a></li>
        <li><a routerLink="/services">Services</a></li>
        <li><a routerLink="/net-banking">Net Banking</a></li>
        <li><a routerLink="/contact-us">Contact Us</a></li>
        <!-- <li><a routerLink="/services/calculator">Calculators</a></li> -->
    </ul>
</aside>
